### ISSUE TITLE
Create requisition fails when `accountSelection` is specified

### ISSUE THREAD

**Issue by sebelik** [nordigen/nordigen-node#37]
**Describe the bug**
When calling the `createRequisition()` method, the server returns status 400 with the following error: `Unknown fields {'accountSelection'} in payload`

**To Reproduce**
1. Call `createRequisition()` and specify `accountSelection: true` in the input
2. Server returns:
```
{
      summary: 'Unknown fields',
      detail: "Unknown fields {'accountSelection'} in payload",
      status_code: 400
}
```

**Expected behavior**
Server returns status code 200 and creates a new requisition

**Additional context**
This might be a typo in the client source code as it sends the parameter as `accountSelection` but according to the API documentation, the parameter is defined as `account_selection`. 

`redirectImmediate` might be susceptible to the same error (untested).

**Comment by victory-sokolov** [comment]
@sebelik Hi, please take a look if its working now.

**Comment by Janjiran** [comment]
Hey @victory-sokolov It's failing for me as well.
It's the same for the `initSession` call which I believe uses the `createRequisition` under the hood.
I'm using the Sandbox for testing.

```js
initSession({
        redirectUrl: "http://localhost:3000/complete/",
        institutionId: institutionId,
        referenceId: randomUUID(),
        accountSelection: true,
});
```

**Comment by Janjiran** [comment]
And also, OP is correct. When you change `accountSelection` from `account_selection` it returns 200 and the object is created however the account selection is still not showing.

**Comment by victory-sokolov** [comment]
@Janjiran Hi, did you tried with the latest library version, `accountSelection` should be fixed.
Note not all institutions support account_selection, but in that case API will return corresponding message

**Comment by Janjiran** [comment]
Yes, I've tried the version 1.2.1 and it's still the same.
You are right, Revolut for example did show the selection UI with their website. So do I understand correctly that the account selection UI is something the bank must have developed and it's not something Nordigen is providing?

**Comment by victory-sokolov** [comment]
In case if bank provides `account_selection` option, then it will be available via API as well
